name: twitter bot

on:
  schedule:
    - cron: "0 0 * * *" 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-dotenv supabase
      - name: execute py script 
        run: |
          python update_authors.py
        env:
          SUPABASE_URL: ${{secrets.SUPABASE_URL}}
          SUPABASE_KEY: ${{secrets.SUPABASE_KEY}}
          DETA_URLL: ${{secrets.DETA_URLL}}
